// generated by stringer -type itemType; DO NOT EDIT

package sproc

import "fmt"

const _itemType_name = "itemErroritemBoolitemCharitemCharConstantitemColonRABitemSemicolonitemEndlineitemEOFitemFielditemIdentifieritemLeftParenitemRightParenitemLeftBracketitemRightBracketitemNumberitemPipeitemSpaceitemStringitemVariableitemStreamitemKeyworditemElseitemIfitemNilitemRangeitemWithitemDefinitionitemFunc"

var _itemType_index = [...]uint16{0, 9, 17, 25, 41, 53, 66, 77, 84, 93, 107, 120, 134, 149, 165, 175, 183, 192, 202, 214, 224, 235, 243, 249, 256, 265, 273, 287, 295}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
